sudo: required
services:
  - docker

before_install:
  - docker build -t react-unit-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run react-unit-test npm test -- --coverage

after_success:
  - docker build -t akkilp/frontend ./frontend
  - docker build -t akkilp/nginx ./nginx
  - docker build -t akkilp/backend ./backend

# Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push to docker-hub
  - docker push akkilp/frontend
  - docker push akkilp/nginx 
  - docker push akkilp/backend